from classvecteur import Vecteur2D, Vecteur3D 
vecteur1 = Vecteur2D() 
vecteur2 = Vecteur2D(1, 2)
print(vecteur1.ToString()) 
print(vecteur2.ToString()) 
print("l'abscisse et l'ordonne des deux vecteurs sont egaux :", vecteur1.Equals(vecteur2)) 
print("Norme de vecteur0 est :", vecteur1.Norme()) 
print("Norme de vecteur1 est :", vecteur2.Norme()) 
vecteur3 = Vecteur3D() 
vecteur4 = Vecteur3D(1, 2, 3) 
print(vecteur3.ToString()) 
print(vecteur4.ToString()) 
print("l'abscisse et l'ordonne des deux vecteurs sont egaux :", vecteur3.Equals(vecteur4)) 
print("Norme de vecteur2 est :", vecteur3.Norme()) 
print("Norme de vecteur3 est :", vecteur4.Norme()) 